version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - docker build -t youtube:latest .
      - docker tag youtube:latest 583455964782.dkr.ecr.us-east-1.amazonaws.com/mytrain:latest
  post_build:
    commands:
      - docker push 583455964782.dkr.ecr.us-east-1.amazonaws.com/mytrain:latest
      - printf '[{"name":"helloWorld","imageUri":"583455964782.dkr.ecr.us-east-1.amazonaws.com/mytrain:latest"}]'    > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
